language: c
os: linux
dist: bionic
addons:
  apt:
    update: true
    packages:
    # Build tools
    - autoconf
    - automake
    - autopoint
    - build-essential
    - git
    - gtk-doc-tools
    - intltool
    - iso-codes
    - libtool
    - libxml2-utils
    - perl
    - xsltproc

    # Desktop app toolkit
    - libasound-dev
    - libatk1.0-dev
    - libcairo-dev
    - libfontconfig1-dev
    - libfreetype6-dev
    - libgdk-pixbuf2.0-dev
    - libglib2.0-dev
    - libgtk2.0-dev
    - libharfbuzz-dev
    - libjson-glib-dev
    - libpango1.0-dev
    - libwebkitgtk-dev
    - libxcursor-dev
    - libxext-dev
    - libxmu-dev
    - libxt-dev
    - shared-mime-info

    # Image libraries
    - libaa1-dev
    - libgexiv2-dev
    - libgs-dev
    - libheif-dev
    - libjpeg-dev
    - libmng-dev
    - libopenexr-dev
    - libopenjp2-7-dev
    - libpng-dev
    - libpoppler-glib-dev
    - libraw-dev
    - librsvg2-dev
    - libtiff-dev
    - libwebp-dev
    - libwmf-dev
    - libxpm-dev

    # Compression libraries
    - libbz2-dev
    - liblzma-dev
    - zlib1g-dev

    # Misc libraries
    - libjson-c-dev
    - libspiro-dev
    - libsuitesparse-dev
    - libumfpack5

    # Python support
    - python-cairo-dev
    - python-dev
    - python-gtk2-dev

    # For the tests
    - appstream-util
    - desktop-file-utils

env:
- INSTALL_PREFIX=/tmp/glimpse-prefix
  SRC_PREFIX=$TRAVIS_BUILD_DIR
  PATH=$INSTALL_PREFIX/bin:$PATH
  PKG_CONFIG_PATH=$INSTALL_PREFIX/lib/pkgconfig:$INSTALL_PREFIX/lib/x86_64-linux-gnu/pkgconfig:$INSTALL_PREFIX/share/pkgconfig:$PKG_CONFIG_PATH
  LD_LIBRARY_PATH=$INSTALL_PREFIX/lib:$INSTALL_PREFIX/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH
  ACLOCAL_FLAGS="-I $INSTALL_PREFIX/share/aclocal $ACLOCAL_FLAGS"
before_install:
- mkdir -p $INSTALL_PREFIX/share/aclocal
- git submodule update --init
before_script:
- cd $SRC_PREFIX/babl
- "./autogen.sh --prefix=$INSTALL_PREFIX --disable-docs"
- make && make install
- cd $SRC_PREFIX/mypaint-brushes
- ./autogen.sh
- "./configure --prefix=$INSTALL_PREFIX"
- make && make install
- cd $SRC_PREFIX/libmypaint
- ./autogen.sh
- "./configure --prefix=$INSTALL_PREFIX"
- make && make install
- cd $SRC_PREFIX/gegl
- "./autogen.sh --prefix=$INSTALL_PREFIX --enable-gtk-doc-html=no --disable-docs"
- make && make install
script:
- cd $SRC_PREFIX
- "./autogen.sh --prefix=$INSTALL_PREFIX --disable-gtk-doc --without-xvfb-run"
- make && make install
- make check
